---

config:
    layout: elk
    securityLevel: 'loose'
---
classDiagram
    direction TB
    namespace HelperClasses{
        class Interval :::done{

        }
        namespace Einheiten{
            class Unit :::done{
            <<abstract>>
                get value : int
                String symbol

            }
            class Euro :::done{
                int centicents
                ...
            }
            class KiloWattHour :::done{
                int wattHours
                ...
            }
        }
    
    }
    namespace log {

        class WallBoxLog ::: done{
            String head;

            String get deviceID
            DateTime get generationDate

            int logID
            TransactionLog[] transactionLogs

            static fromSource() Future<WallBoxLog?>
        }

        class WallBoxTransactionBlock ::: done{
            String id;
            String deviceID
            
            String? get tagID;
            List~MVLine~ mvLines;

            MainLine? start
            MainLine? stop

            toTransaction() Transaction? TODO
        }

        class WallBoxLine ::: done {
         <<abstract>>
            DateTime timeStamp
            KiloWattHour powerLevelWh

            LineType get type

            tryParse(String source) WallBoxLine?
        }

        class MainLine ::: done {
            String tagID
            bool isStart

        }

        class MVLine ::: done 


        note for WallBoxLog  "Entspricht einer einzelnen eingelesenen Log-Datei"
        note for WallBoxTransactionBlock  "Log einer einzelnen Transaktion\nhasStart  bzw hasEnd"
    }
        
    
    class Transaction{
        String id
        String tagID;
        String deviceID;
        DateTime start;
        DateTime end;

        Interval get interval

        KiloWattHours powerUsage;

        getTagAssignment() TagAssignment?
    }

    class TagAssignment{
        String tagID
        String? tagName
        DateTime from
        DateTime? to
        int customerID
        int? userID

        getCustomer(String tagID, DateTime timestamp) Customer?
    }
    class PriceAssignment{
        int customerID
        Euro unitPrice
        DateTime from
        DateTime? to
    }
    class Customer{
        int id
        CompanyData? company;
        PersonalData? personal

        getPriceAtTime (DateTime date) Euro
        getTransactions(DateTime from, DateTime to) Transaction[]
    }

    class User{
        PersonalData? personal
        VehicleData? vehicle
    }

    

    namespace Stammdaten{

    class CompanyData{
        String id
        String companyName
        String street
        String postcode
        String city
        ...
    }

    class PersonalData{
        String prename
        String surname
        String street
        String postcode
        String city
        String phone
        ...
    }

    class VehicleData{
        int id
        String type
        String color
        String licencePlate
        ...
    }
    }
    
    namespace bills{
        class CustomerBill{
            String customerID
            DateTime from
            DateTime to

            TransactionBill[] transactionBills

            getSumBeforeTax() Euro
        }
        class TransactionBill{
            String transactionID
            Euro price
        }
    }
    

    WallBoxLine --|> MainLine : can be
    WallBoxLine --|> MVLine : can be

    WallBoxTransactionBlock "1"*--"n" MVLine: mvs
    WallBoxLog *-- WallBoxTransactionBlock : made of
    WallBoxTransactionBlock "1"*--"0..1" MainLine : start
    WallBoxTransactionBlock "1"*--"0..1" MainLine : stop

    WallBoxTransactionBlock --> Transaction: converts to

    Transaction -- TagAssignment

    TagAssignment o-- Customer
    TagAssignment o.. User
    
    Customer o.. User

    Unit --|> KiloWattHour
    Unit --|> Euro
    User *.. PersonalData
    User *.. VehicleData
    
    Customer "1"*.."n" PersonalData
    Customer "1"*.."n" CompanyData
    Customer "1" *-- "n"PriceAssignment

    note for Customer "erhält Tags & Rechnungen"
    note for User "Für Optionale genauere Zuordnung von Tags\n (ausgehend vom Kunden)"

    note for TagAssignment "wem ist tag x zum Zeitpunkt y zugeordnet?"
    note for PriceAssignment "welchen Preis hat ein Kunde zu Zeitpunkt x?"

    CustomerBill "0,n"<--"1" Customer : pays
    CustomerBill "0,1"*--"1,n" TransactionBill : made up by

    classDef default fill:#A00,stroke:#333,stroke-width:4px;
    classDef inProgress fill:#AA0,stroke:#333,stroke-width:4px;
    classDef done fill:#0A0,stroke:#333,stroke-width:4px, color: black;
      
      
      
