---
title: Datenbank
config:
    layout: elk
---

erDiagram
    direction TB
    
    TRANSACTION }o--o| TAG_ASSIGNMENT : "aquire infos"
    TAG_ASSIGNMENT }o--|| CUSTOMER: "belongs to"
    CUSTOMER ||--|| ADDRESS : "has"
    CUSTOMER ||--|| CONTACT : "has"
    CUSTOMER ||--o| COMPANY_DATA : "has"
    CUSTOMER ||--o| PERSONAL_DATA : "has"
    CUSTOMER ||--o{ PRICE_ASSIGNMENT: "has"

    

    TRANSACTION{
        String tagID PK
        String wb_id FK
        int start_date "=> used to match tag assignment"
        int stop_date 
        int power_usage
    }
    
    TAG_ASSIGNMENT{
        String tagID PK,FK
        int date_from PK
        int? date_to "null => until today"
        int customer_id FK
        int? user_id FK
    }

    
    CUSTOMER{
        String customer_id PK
        String address_id FK
        String contact_id FK

        String? company_id FK
        String? personal_id FK

    }

    PRICE_ASSIGNMENT{
        String customer_id FK
        int price "centicents"
        int date_from
        int? date_to
    }


    COMPANY_DATA{
        String company_id
        String company_name
        String? company_addition
    }
    PERSONAL_DATA{
        String personal_id PK
        String prename
        String surname

        String gemder

    }

    ADDRESS{
        String street
        String house_number
        String? postcode
        String city
        String country
    }

    CONTACT{
        String phone
        String mobile
        String fax
        String email
    }