flowchart

     subgraph "log(Wallbox)"
        direction TB
        subgraph logScan0 
        direction TB
            taLog00
            taLog01
            taLog02
            taLog03
        end
        subgraph logScan1
        direction TB
            taLog10
        end
        subgraph logScan2
        direction TB
            taLog20
            taLog21
            taLog22
            taLog24
        end
        subgraph logScan3
        direction TB
            taLog30
        end
    end